apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    project: expense
    environment: dev
spec:
  containers: 
  - name: nginx
    image: nginx
    env:
    - name: course
      value: 'kubernetes'
    - name: duration
      value: '120hr'