apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    project: expense
    environment: dev
spec:
  containers: 
  - name: nginx
    image: nginx
  # directly configmap data can be accessed as below
    envFrom:
    - ConfigMapRef:
        name: k8cg
# like below, we can individually access configmap data
    # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: k8cg
    #       key: course
    # - name: trainer
    #   valueFrom:
    #     configMapKeyRef:
    #       name: k8cg
    #       key: trainer