apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32760 # this will open nodeport, then connect to clusterip and finally to pod
    # then pod will be accessed from internet
  