apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer ##
  selector:
    project: expense
    environment: dev
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32761