apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: r-set
  # these labels belongs to replicaset resource
  labels:
    app: nginx
    tier: frontend
spec:
# its our need, to maintain number of pods
  replicas: 3
  selector:
  # these labels must be from pod labels
    matchLabels:
      project: expense
      component: frontend
  # this is pod definition
  template:
    metadata:
      name: nginx
      labels:
        project: expense
        component: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx